# Generated by Django 5.1.7 on 2025-03-31 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=2)),
                ('parcelles', models.JSONField()),
                ('mode', models.CharField(max_length=10)),
                ('filters', models.JSONField(null=True)),
                ('points', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_binary', models.BinaryField(null=True)),
                ('model_metrics', models.JSONField(null=True)),
                ('feature_importance', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('selection_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country_code', models.CharField(max_length=2)),
                ('parcelle', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('dataframe_index', models.IntegerField(null=True)),
                ('rendement', models.FloatField(null=True)),
                ('ndvi', models.FloatField(null=True)),
            ],
            options={
                'unique_together': {('session_id', 'country_code', 'parcelle', 'latitude', 'longitude')},
            },
        ),
    ]
