# Generated by Django 5.1.7 on 2025-04-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selectedpoint',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='selectedpoint',
            name='training',
            field=models.BooleanField(help_text='True pour training, False pour prediction', null=True, verbose_name='Mode entraînement'),
        ),
        migrations.AlterUniqueTogether(
            name='selectedpoint',
            unique_together={('session_id', 'country_code', 'parcelle', 'latitude', 'longitude', 'training')},
        ),
    ]
