# Generated by Django 5.1.4 on 2025-01-07 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph', '0001_initial')
    ]

    operations = [

        migrations.CreateModel(
            name='FrenchSyllable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MarsianSyllable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyllablePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('french_syllable1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_french_syllable', to='graph.frenchsyllable')),
                ('french_syllable2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_french_syllable', to='graph.frenchsyllable')),
                ('marsian_syllable1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_marsian_syllable', to='graph.marsiansyllable')),
                ('marsian_syllable2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_marsian_syllable', to='graph.marsiansyllable')),
            ],
            options={
                'unique_together': {('french_syllable1', 'french_syllable2')},
            },
        ),
    ]
