# Generated by Django 5.1.4 on 2025-01-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_add_new_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='frenchsyllable',
            name='cv_pattern',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='marsiansyllable',
            name='cv_pattern',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
