# Generated by Django 5.1.4 on 2025-01-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_frenchsyllable_cv_pattern_marsiansyllable_cv_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='coureur',
            name='nom_marsien',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coureur',
            name='prenom_marsien',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='nom_marsien',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
