# Generated by Django 5.1.4 on 2025-01-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_coureur_nom_marsien_coureur_prenom_marsien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='id_categoriesimplifie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
