# Generated by Django 5.1.4 on 2025-01-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_graphcategoriesimplifiee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GraphCategorieSimplifiee',
            new_name='CategorieSimplifiee',
        ),
    ]
