# Generated by Django 5.1.4 on 2025-01-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0007_rename_graphcategoriesimplifiee_categoriesimplifiee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesimplifiee',
            name='age',
        ),
        migrations.AddField(
            model_name='categoriesimplifiee',
            name='age_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriesimplifiee',
            name='age_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
