# Generated by Django 5.1.4 on 2025-02-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0008_remove_categoriesimplifiee_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatcourse',
            name='categorie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
