# Generated by Django 5.1.4 on 2025-02-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_resultatcourse_categorie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='id_categoriesimplifie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.categoriesimplifiee'),
        ),
        migrations.AlterField(
            model_name='resultatcourse',
            name='categorie_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.categorie'),
        ),
    ]
