# Generated by Django 5.1.1 on 2024-12-05 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coureur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('annee', models.IntegerField()),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CoureurCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.categorie')),
                ('coureur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.coureur')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('coureur', 'categorie', 'annee'), name='unique_coureur_categorie_annee')],
            },
        ),
        migrations.CreateModel(
            name='ResultatCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps', models.DurationField(blank=True, null=True)),
                ('temps2', models.DurationField(blank=True, null=True)),
                ('position', models.IntegerField()),
                ('coureur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.coureur')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.course')),
            ],
            options={
                'unique_together': {('coureur', 'course')},
            },
        ),
    ]
