# Generated by Django 5.1.1 on 2024-12-05 21:32

import django.db.models.deletion
from django.db import migrations, models
from graph.migrationprocess.import_script import import_data
from graph.models import *

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    operations = [import_data(Course, ResultatCourse, Categorie, Coureur, CoureurCategorie)]