"""
Django settings for DataTest project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import sys
from pathlib import Path
import os
from pathlib import Path
import site
BASE_DIR = Path(__file__).resolve().parent.parent  # Définition standard

# Build paths inside the project like this: BASE_DIR / 'subdir'.
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000']
VENV_PATH = sys.prefix  # Chemin de l'environnement virtuel

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'node_modules'),
    #os.path.join(BASE_DIR, 'graph','static'),
    #os.path.join(BASE_DIR, 'bubble_sort','static'),
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR , r'.venv/Lib/site-packages/dash_renderer'),
    os.path.join(BASE_DIR, r'.venv/Lib/site-packages/plotly'),  # Fichiers Plotly
]
COMPRESS_ENABLED = False
PLOTLY_DASH = {
    'cache_timeout': 3600,
    'storage_type': 'session',
    'http_poke_interval': 30
}
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',  # Pour usage local uniquement
    }
}
# Ajout des configurations CORS
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django_plotly_dash.finders.DashAssetFinder'  # Uniquement ce finder
]

NPM_FILE_PATTERNS = {
    'plotly.js-dist': ['plotly.js']
}
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jfld%(s@^c*@70jz37b*3(zzxypp=wwp9d--qmj!&j26t(1&ex'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

JSON_SERIALIZER = {
    'ensure_ascii': False,
    'separators': (',', ':'),
    'indent': None
}


# Application definition

INSTALLED_APPS = [
    'dashapp.apps.DashappConfig',
    'graph.apps.GraphConfig',
    'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'test_without_migrations',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bubble_sort.apps.BubbleSortConfig',
    'agri.apps.AgriConfig',
    'django_plotly_dash'
]
# Add this line below STATIC_URL
X_FRAME_OPTIONS = 'SAMEORIGIN'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_plotly_dash.middleware.BaseMiddleware',  # Doit être après SessionMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]


ROOT_URLCONF = 'DataTest.urls'

PLOTLY_COMPONENTS = [
    'dash_core_components',
    'dash_html_components',
    'dash_renderer',
    'dash_bootstrap_components'
]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']  # Fonctionne si BASE_DIR est un objet Path
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DataTest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DJANGO_COMMANDER_COMMAND_FOLDERS = [
    os.path.abspath(os.path.join('DataTest\\graph\\management', "commands")),
]

LOGIN_URL = '/login/'  # Ajustez le chemin selon votre configuration

LOGIN_REDIRECT_URL = '/'  # Redirige vers la page d'accueil après la connexion

CELERY_BROKER_URL = "redis://localhost:6379"
CELERY_RESULT_BACKEND = "redis://localhost:6379"