# Generated by Django 5.1.4 on 2025-01-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble_sort', '0002_classementbubble_bubble_classement'),
    ]

    operations = [
        migrations.AddField(
            model_name='classementbubble',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
