# Generated by Django 5.1.4 on 2025-02-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble_sort', '0003_classementbubble_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='bubble',
            name='height',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='bubble',
            name='width',
            field=models.IntegerField(default=200),
        ),
    ]
