# Generated by Django 5.1.4 on 2025-02-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble_sort', '0004_bubble_height_bubble_width'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bubble',
            options={'ordering': ['position'], 'verbose_name': 'Bulle', 'verbose_name_plural': 'Bulles'},
        ),
        migrations.AddField(
            model_name='bubble',
            name='title',
            field=models.CharField(default='Nouvelle Bulle', max_length=200),
        ),
        migrations.AddField(
            model_name='classementbubble',
            name='color_end',
            field=models.CharField(default='#00FF00', max_length=7),
        ),
        migrations.AddField(
            model_name='classementbubble',
            name='color_start',
            field=models.CharField(default='#FF0000', max_length=7),
        ),
        migrations.AlterField(
            model_name='bubble',
            name='width',
            field=models.IntegerField(default=1000),
        ),
    ]
