# Generated by Django 5.1.4 on 2025-02-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble_sort', '0005_alter_bubble_options_bubble_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color_code', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'verbose_name': 'Préréglage de couleur',
                'verbose_name_plural': 'Préréglages de couleurs',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='classementbubble',
            name='color_end',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='classementbubble',
            name='color_start',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
