# Generated by Django 5.1.4 on 2025-02-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble_sort', '0006_colorpreset_alter_classementbubble_color_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classementbubble',
            name='color_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_color_classements', to='bubble_sort.colorpreset', verbose_name='Couleur de fin'),
        ),
        migrations.AlterField(
            model_name='classementbubble',
            name='color_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_color_classements', to='bubble_sort.colorpreset', verbose_name='Couleur de début'),
        ),
    ]
